// Code generated by MockGen. DO NOT EDIT.
// Source: device.go

// Package ethernet is a generated GoMock package.
package ethernet

import (
	reflect "reflect"

	error "github.com/42milez/ProtocolStack/src/error"
	gomock "github.com/golang/mock/gomock"
)

// MockIDevice is a mock of IDevice interface.
type MockIDevice struct {
	ctrl     *gomock.Controller
	recorder *MockIDeviceMockRecorder
}

// MockIDeviceMockRecorder is the mock recorder for MockIDevice.
type MockIDeviceMockRecorder struct {
	mock *MockIDevice
}

// NewMockIDevice creates a new mock instance.
func NewMockIDevice(ctrl *gomock.Controller) *MockIDevice {
	mock := &MockIDevice{ctrl: ctrl}
	mock.recorder = &MockIDeviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDevice) EXPECT() *MockIDeviceMockRecorder {
	return m.recorder
}

// BroadcastEthAddr mocks base method.
func (m *MockIDevice) BroadcastEthAddr() EthAddr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastEthAddr")
	ret0, _ := ret[0].(EthAddr)
	return ret0
}

// BroadcastEthAddr indicates an expected call of BroadcastEthAddr.
func (mr *MockIDeviceMockRecorder) BroadcastEthAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastEthAddr", reflect.TypeOf((*MockIDevice)(nil).BroadcastEthAddr))
}

// Close mocks base method.
func (m *MockIDevice) Close() error.E {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error.E)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIDeviceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIDevice)(nil).Close))
}

// DevName mocks base method.
func (m *MockIDevice) DevName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DevName")
	ret0, _ := ret[0].(string)
	return ret0
}

// DevName indicates an expected call of DevName.
func (mr *MockIDeviceMockRecorder) DevName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DevName", reflect.TypeOf((*MockIDevice)(nil).DevName))
}

// DevType mocks base method.
func (m *MockIDevice) DevType() DevType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DevType")
	ret0, _ := ret[0].(DevType)
	return ret0
}

// DevType indicates an expected call of DevType.
func (mr *MockIDeviceMockRecorder) DevType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DevType", reflect.TypeOf((*MockIDevice)(nil).DevType))
}

// Down mocks base method.
func (m *MockIDevice) Down() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Down")
}

// Down indicates an expected call of Down.
func (mr *MockIDeviceMockRecorder) Down() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Down", reflect.TypeOf((*MockIDevice)(nil).Down))
}

// Equal mocks base method.
func (m *MockIDevice) Equal(dev IDevice) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Equal", dev)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Equal indicates an expected call of Equal.
func (mr *MockIDeviceMockRecorder) Equal(dev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Equal", reflect.TypeOf((*MockIDevice)(nil).Equal), dev)
}

// EthAddr mocks base method.
func (m *MockIDevice) EthAddr() EthAddr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EthAddr")
	ret0, _ := ret[0].(EthAddr)
	return ret0
}

// EthAddr indicates an expected call of EthAddr.
func (mr *MockIDeviceMockRecorder) EthAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EthAddr", reflect.TypeOf((*MockIDevice)(nil).EthAddr))
}

// IsUp mocks base method.
func (m *MockIDevice) IsUp() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUp")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUp indicates an expected call of IsUp.
func (mr *MockIDeviceMockRecorder) IsUp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUp", reflect.TypeOf((*MockIDevice)(nil).IsUp))
}

// MTU mocks base method.
func (m *MockIDevice) MTU() uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MTU")
	ret0, _ := ret[0].(uint16)
	return ret0
}

// MTU indicates an expected call of MTU.
func (mr *MockIDeviceMockRecorder) MTU() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MTU", reflect.TypeOf((*MockIDevice)(nil).MTU))
}

// Open mocks base method.
func (m *MockIDevice) Open() error.E {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open")
	ret0, _ := ret[0].(error.E)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockIDeviceMockRecorder) Open() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockIDevice)(nil).Open))
}

// PeerEthAddr mocks base method.
func (m *MockIDevice) PeerEthAddr() EthAddr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeerEthAddr")
	ret0, _ := ret[0].(EthAddr)
	return ret0
}

// PeerEthAddr indicates an expected call of PeerEthAddr.
func (mr *MockIDeviceMockRecorder) PeerEthAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeerEthAddr", reflect.TypeOf((*MockIDevice)(nil).PeerEthAddr))
}

// Poll mocks base method.
func (m *MockIDevice) Poll(terminate bool) error.E {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", terminate)
	ret0, _ := ret[0].(error.E)
	return ret0
}

// Poll indicates an expected call of Poll.
func (mr *MockIDeviceMockRecorder) Poll(terminate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockIDevice)(nil).Poll), terminate)
}

// PrivDevName mocks base method.
func (m *MockIDevice) PrivDevName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivDevName")
	ret0, _ := ret[0].(string)
	return ret0
}

// PrivDevName indicates an expected call of PrivDevName.
func (mr *MockIDeviceMockRecorder) PrivDevName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivDevName", reflect.TypeOf((*MockIDevice)(nil).PrivDevName))
}

// Transmit mocks base method.
func (m *MockIDevice) Transmit(dst EthAddr, payload []byte, typ EthType) error.E {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transmit", dst, payload, typ)
	ret0, _ := ret[0].(error.E)
	return ret0
}

// Transmit indicates an expected call of Transmit.
func (mr *MockIDeviceMockRecorder) Transmit(dst, payload, typ interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transmit", reflect.TypeOf((*MockIDevice)(nil).Transmit), dst, payload, typ)
}

// Up mocks base method.
func (m *MockIDevice) Up() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Up")
}

// Up indicates an expected call of Up.
func (mr *MockIDeviceMockRecorder) Up() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Up", reflect.TypeOf((*MockIDevice)(nil).Up))
}
