codecov:
  require_ci_to_pass: yes
coverage:
  ignore:
    - src/**/*mock*.go
  patch:
    default:
      threshold: 0%
  precision: 2
  range: 50...80
  round: down
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      macro: no
      method: no
comment:
  behavior: default
  layout: reach, diff, flags, files, footer
  require_changes: no
