codecov:
  require_ci_to_pass: yes
coverage:
  patch:
    default:
      threshold: 0%
  precision: 2
  round: down
  range: "50...80"
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
