codecov:
  require_ci_to_pass: yes
comment:
  behavior: default
  layout: reach, diff, flags, files, footer
  require_changes: no
coverage:
  precision: 2
  range: 60...80
  round: down
  status:
    patch:
      default:
        threshold: 0%
ignore:
  - src/**/*_mock.go
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      macro: no
      method: no
