services:
  base: &base
    build:
      context: .
      dockerfile: Dockerfile
    image: protocol-stack:latest
    stdin_open: true
    tty: true
  test:
    <<: *base
    command: make test
    volumes:
      - type: volume
        source: gopath
        target: /go
        volume:
          nocopy: false
      - type: volume
        source: goroot
        target: /usr/local/go
        volume:
          nocopy: false
      - type: bind
        source: .
        target: /app
volumes:
  gopath:
    driver: local
  goroot:
    driver: local
