// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/k12n3ud0n/Workspace/ProtocolStack/src/syscall/epoll_create1.go

// Package mock_syscall is a generated GoMock package.
package mock_syscall

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEpollCreate1Interface is a mock of EpollCreate1Interface interface.
type MockEpollCreate1Interface struct {
	ctrl     *gomock.Controller
	recorder *MockEpollCreate1InterfaceMockRecorder
}

// MockEpollCreate1InterfaceMockRecorder is the mock recorder for MockEpollCreate1Interface.
type MockEpollCreate1InterfaceMockRecorder struct {
	mock *MockEpollCreate1Interface
}

// NewMockEpollCreate1Interface creates a new mock instance.
func NewMockEpollCreate1Interface(ctrl *gomock.Controller) *MockEpollCreate1Interface {
	mock := &MockEpollCreate1Interface{ctrl: ctrl}
	mock.recorder = &MockEpollCreate1InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEpollCreate1Interface) EXPECT() *MockEpollCreate1InterfaceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockEpollCreate1Interface) Exec() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockEpollCreate1InterfaceMockRecorder) Exec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockEpollCreate1Interface)(nil).Exec))
}
