// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/k12n3ud0n/Workspace/ProtocolStack/src/syscall/socket.go

// Package mock_syscall is a generated GoMock package.
package mock_syscall

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSocketSyscallInterface is a mock of SocketSyscallInterface interface.
type MockSocketSyscallInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSocketSyscallInterfaceMockRecorder
}

// MockSocketSyscallInterfaceMockRecorder is the mock recorder for MockSocketSyscallInterface.
type MockSocketSyscallInterfaceMockRecorder struct {
	mock *MockSocketSyscallInterface
}

// NewMockSocketSyscallInterface creates a new mock instance.
func NewMockSocketSyscallInterface(ctrl *gomock.Controller) *MockSocketSyscallInterface {
	mock := &MockSocketSyscallInterface{ctrl: ctrl}
	mock.recorder = &MockSocketSyscallInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocketSyscallInterface) EXPECT() *MockSocketSyscallInterfaceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockSocketSyscallInterface) Exec() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockSocketSyscallInterfaceMockRecorder) Exec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockSocketSyscallInterface)(nil).Exec))
}
