name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Compile
        run: make compile
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: codecov/codecov-action@v1
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run all tests
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        run: bash <(curl -s https://codecov.io/bash)
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
