name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Compile
        run: make compile RELEASE=true
      - name: Archive
        run: |
          tar -zcvf ./bin/tcp_client-linux64.tar.gz ./bin/tcp_client
          tar -zcvf ./bin/tcp_server-linux64.tar.gz ./bin/tcp_server
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./bin/tcp_client.tar.gz
            ./bin/tcp_server.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
